name: metroid
channels:
  - conda-forge
dependencies:
  - python=3.13.12
  - scikit-learn
  - scikit-image
  - notebook
  - pandas
  - astropy
  - scipy
  - jupyterlab
  - matplotlib
  - numpy
  - galsim
  - rubin-sim
  - black
  - pytest
  - speclite
